//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDepartanetv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobantesPago
    {
        public int id { get; set; }
        public Nullable<int> id_producto { get; set; }
        public string id_usuario { get; set; }
        public string descripcion { get; set; }
        public string nom_archivo { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_validado { get; set; }
        public string observaciones { get; set; }
    }
}
