//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDepartanetv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inquilinos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_inquilinos()
        {
            this.rel_inquilinodepto = new HashSet<rel_inquilinodepto>();
        }
    
        public int id { get; set; }
        public string appaterno { get; set; }
        public string apmaterno { get; set; }
        public string nombre { get; set; }
        public string tel_cel { get; set; }
        public string tel_casa { get; set; }
        public string correo { get; set; }
        public int tipo_inquilino { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_inquilinodepto> rel_inquilinodepto { get; set; }
    }
}
