//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDepartanetv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fichadepartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_fichadepartamento()
        {
            this.rel_inquilinodepto = new HashSet<rel_inquilinodepto>();
        }
    
        public int id { get; set; }
        public string edificio { get; set; }
        public string numero { get; set; }
        public string piso { get; set; }
        public string lote { get; set; }
        public string manzana { get; set; }
        public string observaciones { get; set; }
        public int estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_inquilinodepto> rel_inquilinodepto { get; set; }
    }
}
